### ISSUE TITLE
Change default description for 200 status code

### ISSUE THREAD

**Issue by IvanGoncharov** [apigee-127/swagger-converter#23]
`No response was specified` string is simply ugly.
For `200` good candidate is `OK`.

If required, user could be notify by warning mechanism.
It could be a simple callback which receive warning string as argument.

I can implement it as PR.

**Comment by mohsen1** [comment]
Because 2.0 requires you to specify a response object we are making up the 200 response. The description is `No response was specified` for this reason.

I like the idea of having a mechanism for overloading the default behavior. Please make a pull request, I'll help you to get it merged. Make sure you update the documentations and write tests for it.

**Comment by mohsen1** [comment]
@IvanGoncharov any updates on this?

**Comment by IvanGoncharov** [comment]
I still want to implement this, but I shift my efforts to #26.
